name: flutter_segment
description: Flutter implementation of Segment Analytics for iOS, Android and Web
version: 0.0.8
authors:
  - Kevin Luecke <kevin@claimsforce.com>
  - Maik Schmidt <maik@claimsforce.com>
  - Vinicius Zani <vinicius@queroanimo.com>
homepage: https://www.claimsforce.com
repository: https://github.com/claimsforce-gmbh/flutter-segment

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_segment
        pluginClass: FlutterSegmentPlugin
      ios:
        pluginClass: FlutterSegmentPlugin
      web:
        pluginClass: SegmentPlatformWeb
        fileName: segment_platform_web.dart
